name: build docker image and push to dockerhub

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract version from tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "version_without_v=${VERSION#v}" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
            echo "version_without_v=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            bentopdf/bentopdf:latest
            bentopdf/bentopdf:${{ steps.version.outputs.version_without_v }}
            bentopdf/bentopdf:${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64
